name: dhis2_flutter_toolkit_demo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.0.2
  dhis2_flutter_toolkit:
    path : /home/allen/Projects/HISP/Mobile/dhis2-flutter-toolkit
    # git:
    #   url: https://github.com/hisptz/dhis2_flutter_toolkit.git
    #   ref: develop
  fluttertoast: ^8.2.4
  dart_date: ^1.3.2
  provider: ^6.1.2
  collection: ^1.18.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  go_router_builder: ^2.5.1
  
flutter:
  uses-material-design: true
  assets:
   - assets/logos/
  #   - images/a_dot_ham.jpeg

 
